sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t dt5513/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dt5513/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "udemy-docker-frontend"
  env: "UdemyDockerFrontend-env"
  bucket_name: "elasticbeanstalk-eu-west-2-020225586511"
  bucket_path: "udemy_docker_frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
